export const VOICE_SAMPLE_TARGET = 6;
export const VOICE_MIN_CLIP_SEC = 8;
export const VOICE_ADVISABLE_CLIP_SEC = 20;
export const VOICE_TARGET_TOTAL_SEC = 90;

const VOICE_UI = {
  es: {
    profileName: 'Nombre',
    voiceReady: 'Voz lista',
    voiceNotReady: 'Sin voz',
    voiceProfile: 'Voz',
    voiceCopy: 'Graba 6 clips con tu voz natural, de unos 20–30 segundos cada uno.',
    samplesRecorded: 'grabadas',
    samplesSaved: 'Audios guardados',
    resetSamples: 'Reiniciar audios',
    needsUpdate: 'Muestras cambiadas — actualiza la voz.',
    elevenlabsMissing: 'Falta ELEVENLABS_API_KEY en .env.',
    readNext: 'Lee',
    readingNow: 'Leyendo',
    recordSample: 'Grabar',
    savingSample: 'Guardando muestra…',
    stopSample: 'Guardar',
    cancelRecording: 'Cancelar',
    createVoice: 'Crear voz',
    updateVoice: 'Actualizar voz',
    creatingVoice: 'Creando…',
    samplesComplete: 'Configurando voz…',
    enoughSamples: 'Listo',
    setupVoice: 'Configurar voz',
    savingSample: 'Guardando…',
    discardRecording: 'Descartar',
    recordingBlocked: 'Ya tienes 6 muestras.',
    durationCaptured: 'voz capturada',
    recordTooShort: 'Graba un poco más — al menos 8 segundos.',
    voiceSetupFailed: 'Error:',
    deleteSample: 'Eliminar muestra',
    switchUser: 'Cerrar sesión',
    editUser: 'Editar perfil',
    recordAgain: 'Grabar de nuevo',
    confirmRecordAgain: '¿Reemplazar todas las muestras? Grabarás 6 de nuevo.',
    recoveryPhrase: 'Frase de recuperación',
    showRecoveryPhrase: 'Ver seed',
    hideRecoveryPhrase: 'Ocultar seed',
    recoveryPhraseMissing: 'No está guardada en este dispositivo. Usa la frase que anotaste al crear la cuenta.',
    copyPhrase: 'Copiar frase',
    copiedPhrase: 'Copiado',
    couldNotCopy: 'No se pudo copiar',
    createAccount: 'Crear cuenta',
    createAccountFailed: 'No se pudo crear la cuenta.',
    cloneVoiceLanguagesFootnote: 'Tu voz funciona en',
    cloneVoiceLanguagesV2: 'Multilingüe v2',
    cloneVoiceLanguagesV3: 'Eleven v3',
    showCloneVoiceLanguages: 'Ver idiomas con tu voz',
    hideCloneVoiceLanguages: 'Ocultar idiomas con tu voz',
  },
  th: {
    profileName: 'ชื่อ',
    voiceReady: 'เสียงพร้อม',
    voiceNotReady: 'ยังไม่มีเสียง',
    voiceProfile: 'เสียง',
    voiceCopy: 'บันทึก 6 คลิปด้วยน้ำเสียงตามธรรมชาติ คลิปละประมาณ 20–30 วินาที',
    samplesRecorded: 'บันทึกแล้ว',
    samplesSaved: 'เสียงที่บันทึกแล้ว',
    resetSamples: 'รีเซ็ตเสียงที่บันทึก',
    needsUpdate: 'ตัวอย่างเปลี่ยน — อัปเดตเสียง',
    elevenlabsMissing: 'ไม่มี ELEVENLABS_API_KEY ใน .env',
    readNext: 'อ่าน',
    readingNow: 'กำลังอ่าน',
    recordSample: 'บันทึก',
    savingSample: 'กำลังบันทึก…',
    stopSample: 'บันทึก',
    cancelRecording: 'ยกเลิก',
    createVoice: 'สร้างเสียง',
    updateVoice: 'อัปเดตเสียง',
    creatingVoice: 'กำลังสร้าง…',
    samplesComplete: 'กำลังตั้งค่า…',
    enoughSamples: 'ครบแล้ว',
    setupVoice: 'ตั้งค่าเสียง',
    savingSample: 'กำลังบันทึก…',
    discardRecording: 'ยกเลิก',
    recordingBlocked: 'มีครบ 6 ตัวอย่างแล้ว',
    durationCaptured: 'เสียงที่บันทึกแล้ว',
    recordTooShort: 'บันทึกให้นานขึ้น — อย่างน้อย 8 วินาที',
    voiceSetupFailed: 'ผิดพลาด:',
    deleteSample: 'ลบตัวอย่าง',
    switchUser: 'ปิดเซสชัน',
    editUser: 'แก้ไขโปรไฟล์',
    recordAgain: 'บันทึกใหม่',
    confirmRecordAgain: 'แทนที่ตัวอย่างทั้งหมด? คุณจะบันทึกใหม่ 6 ครั้ง',
    recoveryPhrase: 'วลีกู้คืน',
    showRecoveryPhrase: 'Show seed',
    hideRecoveryPhrase: 'Hide seed',
    recoveryPhraseMissing: 'ไม่ได้บันทึกไว้ในอุปกรณ์นี้ ใช้วลีที่คุณบันทึกตอนสร้างบัญชี',
    copyPhrase: 'Copy phrase',
    copiedPhrase: 'Copied',
    couldNotCopy: 'Could not copy',
    createAccount: 'Create account',
    createAccountFailed: 'Could not create account.',
    cloneVoiceLanguagesFootnote: 'เสียงของคุณใช้ได้ใน',
    cloneVoiceLanguagesV2: 'Multilingual v2',
    cloneVoiceLanguagesV3: 'Eleven v3',
    showCloneVoiceLanguages: 'Show voice languages',
    hideCloneVoiceLanguages: 'Hide voice languages',
  },
  en: {
    profileName: 'Name',
    voiceReady: 'Voice ready',
    voiceNotReady: 'No voice yet',
    voiceProfile: 'Voice',
    voiceCopy: 'Record 6 clips in your natural voice, about 20–30 seconds each.',
    samplesRecorded: 'recorded',
    samplesSaved: 'Saved recordings',
    resetSamples: 'Reset recordings',
    needsUpdate: 'Samples changed — update voice.',
    elevenlabsMissing: 'Missing ELEVENLABS_API_KEY in .env.',
    readNext: 'Read',
    readingNow: 'Reading',
    recordSample: 'Record',
    savingSample: 'Saving sample…',
    stopSample: 'Save',
    cancelRecording: 'Cancel',
    createVoice: 'Create voice',
    updateVoice: 'Update voice',
    creatingVoice: 'Creating…',
    samplesComplete: 'Setting up voice…',
    enoughSamples: 'Done',
    setupVoice: 'Set up voice',
    savingSample: 'Saving…',
    discardRecording: 'Discard',
    recordingBlocked: '6 samples full.',
    durationCaptured: 'voice captured',
    recordTooShort: 'Record a little longer — at least 8 seconds.',
    voiceSetupFailed: 'Error:',
    deleteSample: 'Delete sample',
    switchUser: 'Close session',
    editUser: 'Edit profile',
    recordAgain: 'Record again',
    confirmRecordAgain: 'Replace all samples? You’ll record 6 again.',
    recoveryPhrase: 'Recovery phrase',
    showRecoveryPhrase: 'Show seed',
    hideRecoveryPhrase: 'Hide seed',
    recoveryPhraseMissing: 'Not saved on this device. Use the phrase you wrote down when you created your account.',
    copyPhrase: 'Copy phrase',
    copiedPhrase: 'Copied',
    couldNotCopy: 'Could not copy',
    createAccount: 'Create account',
    createAccountFailed: 'Could not create account.',
    cloneVoiceLanguagesFootnote: 'Your voice works in',
    cloneVoiceLanguagesV2: 'Multilingual v2',
    cloneVoiceLanguagesV3: 'Eleven v3',
    showCloneVoiceLanguages: 'Show voice languages',
    hideCloneVoiceLanguages: 'Hide voice languages',
  },
};

const VOICE_PROMPTS = {
  es: [
    'Hola, esta es mi voz. Estoy grabando estas muestras más largas para mi perfil personal en Lingu.ooo. Quiero hablar con naturalidad y claridad, como lo haría con alguien que conozco bien en una conversación cotidiana — relajado, sin prisa y fácil de entender desde la primera palabra.',
    '¿Cómo estás hoy? ¿Te ha ido bien esta semana, o ha pasado algo que no esperabas y que todavía te tiene pensando — algo pequeño que se te quedó grabado o algo más grande que cambió tus planes por completo?',
    '¡Qué buena noticia! Me alegra mucho escucharlo, y quiero que mi entusiasmo se note en la voz — en el ritmo, en el tono y en cómo enfatizo ciertas palabras para que el sentimiento sea inconfundible y suene completamente genuino!',
    'A veces explico las cosas con calma y claridad. Hablo a un ritmo constante, dejo pausas naturales entre frases e intento que cada palabra se entienda sin sonar apresurado ni como si leyera un guion que otra persona escribió para mí.',
    'Cuando leo un mensaje más largo en voz alta, me detengo y me pregunto — ¿de verdad crees que la entonación cambia tanto cuando convertimos una frase simple en una pregunta sincera, una que demuestra que te importa de verdad la respuesta?',
    '¡Vaya diferencia que marca un solo tono! Las mismas palabras pueden sonar curiosas, sorprendidas o encantadas — y quiero que mi voz transmita toda esa energía cuando hablo, para que la gente escuche exactamente lo que quiero decir!',
  ],
  th: [
    'สวัสดี นี่คือเสียงของฉัน ฉันกำลังบันทึกตัวอย่างที่ยาวขึ้นเหล่านี้เพื่อสร้างโปรไฟล์เสียงส่วนตัวใน Lingu.ooo ฉันต้องการพูดอย่างเป็นธรรมชาติและชัดเจน เหมือนคุยกับคนที่รู้จักดีในชีวิตประจำวัน — ผ่อนคลาย ไม่รีบ และเข้าใจง่ายตั้งแต่คำแรก',
    'วันนี้เป็นอย่างไรบ้าง สัปดาห์นี้เป็นไปด้วยดีไหม หรือมีเรื่องที่คุณไม่คาดคิดเกิดขึ้นและยังคิดถึงอยู่เรื่อย ๆ — เรื่องเล็ก ๆ ที่ติดอยู่ในหัว หรือเรื่องใหญ่ที่เปลี่ยนแผนของคุณไปเลย?',
    'ข่าวดีมากเลย! ฉันดีใจจริง ๆ ที่ได้ยิน และอยากให้ความตื่นเต้นนั้นออกมาในเสียงของฉัน — ทั้งจังหวะ โทน และการเน้นคำบางคำ เพื่อให้ความรู้สึกนั้นชัดเจนและฟังดูจริงใจอย่างแท้จริง!',
    'บางครั้งฉันอธิบายอย่างใจเย็นและชัดเจน ฉันพูดด้วยจังหวะสม่ำเสมอ หยุดพักตามธรรมชาติระหว่างวลี และพยายามให้ทุกคำเข้าใจง่ายโดยไม่ฟังดูรีบหรือเหมือนกำลังอ่านสคริปต์ที่คนอื่นเขียนให้ฉัน',
    'เมื่อฉันอ่านข้อความที่ยาวขึ้น ฉันอาจหยุดแล้วถามตัวเอง — คุณคิดจริง ๆ ว่าน้ำเสียงเปลี่ยนมากแค่ไหนเมื่อเราเปลี่ยนประโยคธรรมดาให้กลายเป็นคำถามจริงจัง คำถามที่แสดงว่าคุณใส่ใจคำตอบจริง ๆ?',
    'น่าทึ่งมากที่โทนเดียวสร้างความรู้สึกต่างกันได้ขนาดนี้! คำเดิม ๆ อาจฟังดูสงสัย ประหลาดใจ หรือดีใจ — และฉันอยากให้เสียงของฉันสื่อพลังงานนั้นเมื่อพูด เพื่อให้คนอื่นได้ยินสิ่งที่ฉันต้องการสื่ออย่างชัดเจน!',
  ],
  en: [
    'Hello, this is my voice. I am recording these longer samples for my personal profile on Lingu.ooo. I want to speak naturally and clearly, just like I would when talking to someone I know well in everyday conversation — relaxed, unhurried, and easy to understand from the very first word.',
    'How are you today? Has your week been going well, or did something unexpected happen that you are still thinking about — something small that stuck with you, or something bigger that changed your plans completely?',
    'That is wonderful news! I am really happy to hear it, and I want my excitement to come through in my voice — in my pace, my tone, and the way I emphasize certain words so the feeling is unmistakable and sounds completely genuine!',
    'Sometimes I explain things calmly and clearly. I speak at a steady pace, leave natural pauses between phrases, and try to make every word easy to understand without sounding rushed or like I am reading from a script that someone else wrote for me.',
    'When I read a longer message out loud, I might pause and ask — do you really think intonation changes that much when we turn a simple sentence into a genuine question, one that shows you truly care about the answer?',
    'What a difference a single tone can make! The same words can sound curious, surprised, or delighted — and I want my voice to carry all of that energy when I speak, so people hear exactly what I mean!',
  ],
};

export function resolveVoiceLanguage(code) {
  const lang = String(code || 'en').toLowerCase().trim();
  if (VOICE_PROMPTS[lang]) return lang;
  return 'en';
}

export function getVoiceUi(code) {
  const lang = resolveVoiceLanguage(code);
  return VOICE_UI[lang];
}

export function getVoicePrompts(code) {
  const lang = resolveVoiceLanguage(code);
  return VOICE_PROMPTS[lang];
}

export function getVoicePrompt(code, sampleCount) {
  const prompts = getVoicePrompts(code);
  return prompts[sampleCount % prompts.length];
}
